models:
  default:
    coder:
      api_key: ""
      base_url: https://openrouter.ai/api/v1
      display_name: google/gemini-3-flash-preview (OpenRouter)
      model: google/gemini-3-flash-preview
      provider: OpenRouter
    critic:
      api_key: ""
      base_url: https://openrouter.ai/api/v1
      display_name: google/gemini-3-flash-preview (OpenRouter)
      model: google/gemini-3-flash-preview
      provider: OpenRouter
    fixer:
      api_key: ""
      base_url: https://openrouter.ai/api/v1
      display_name: google/gemini-3-flash-preview (OpenRouter)
      model: google/gemini-3-flash-preview
      provider: OpenRouter
    proposer:
      api_key: ""
      base_url: https://openrouter.ai/api/v1
      display_name: google/gemini-3-flash-preview (OpenRouter)
      model: google/gemini-3-flash-preview
      provider: OpenRouter
    synthesizer:
      api_key: ""
      base_url: https://openrouter.ai/api/v1
      display_name: google/gemini-3-flash-preview (OpenRouter)
      model: google/gemini-3-flash-preview
      provider: OpenRouter
parameters:
  max_tokens: 4096
  temperature:
    coder: 0.2
    critic: 0.3
    fixer: 0.1
    proposer: 0.9
    synthesizer: 0.5
providers:
- api_key: ""
  base_url: https://open.bigmodel.cn/api/paas/v4
  main_model: glm-4.7
  models:
  - glm-4.7
  name: 智谱GLM
  note: ''
  template: null
  website: https://open.bigmodel.cn/
- api_key: ""
  base_url: https://api.deepbricks.ai/v1
  main_model: claude-sonnet-4.5
  models:
  - claude-sonnet-4.5
  name: 自定义配置
  note: ''
  template: 自定义
  website: https://api.deepbricks.ai
- api_key: ""
  base_url: https://openrouter.ai/api/v1
  main_model: google/gemini-3-flash-preview
  models:
  - google/gemini-3-flash-preview
  name: OpenRouter
  note: ''
  template: OpenRouter
  website: https://openrouter.ai
use_same_model: true



